In [3]:
import numpy as np

In [2]:
list1 = [1,2,3]
print("list1 : ", list1)
print("list1 type : ", type(list1))

array1 = np.array(list1)
print("list1 : ", array1)
print(type(array1))

list1 :  [1, 2, 3]
list1 type :  <class 'list'>
list1 :  [1 2 3]
<class 'numpy.ndarray'>


In [3]:
array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print(type(array2))
print(array2.shape)

array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [8]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원' .format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


In [10]:
list1 = [1,2,3]
print(type(list1))
print(list1)
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
[1, 2, 3]
<class 'numpy.ndarray'>
[1 2 3] int32


In [11]:
list2 = [1,2, 'test']
print(list2)
array2 = np.array(list2)
print(array2, array2.dtype)

[1, 2, 'test']
['1' '2' 'test'] <U11


In [12]:
list3 = [1,2,3.0]
print(list3)
array3 = np.array(list3)
print(array3, array3.dtype)

[1, 2, 3.0]
[1. 2. 3.] float64


In [13]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1 , 2.1 , 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [15]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [19]:
zero_array = np.zeros((3,2),dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [22]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2,5)
print(array2)

array3 = array1.reshape(5,2)
print(array3)

array1.reshape(4,3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [23]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print(array2.shape)
print(array2)

array3 = array1.reshape(5,-1)
print(array3.shape)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [4]:
array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value)
print(type(value))

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>


In [7]:
print(array1[-2], array1[-1])

8 9


In [8]:
array1[0] = 9
array1[-1] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [9]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0,0])
print(array2d[0,1])
print(array2d[1,0])
print(array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


In [10]:
array1 = np.arange(start=1, stop=10)
print(array1)
array3 = array1[0:3]
print(array3)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [11]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)
array5 = array1[3:]
print(array5)
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [13]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(array2d[0:2, 0:2])
print(array2d[1:3, 0:3])
print(array2d[1:3, :])
print(array2d[:,:])
print(array2d[:2,1:])
print(array2d[:2,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]


In [14]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print(array3)

array4 = array2d[[0,2],0:2]
print(array4)

array5 = array2d[[0,1]]
print(array5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [7 8]]
[[1 2 3]
 [4 5 6]]


In [15]:
array1d = np.arange(start=1, stop=10)
print(array1d)

print(array1d>5)

var1 = array1d>5
print(var1)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[False False False False False  True  True  True  True]


In [16]:
print(array1d)
array3 = array1d[array1d>5]
print(array3)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [17]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


In [19]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0,9):
    if array1d[i]>5 :
        target.append(array1d[i])
       
print(target)
array_selected = np.array(target)
print(array_selected)

[6, 7, 8, 9]
[6 7 8 9]


In [20]:
org_array = np.array([3,1,9,5])
print(org_array)

sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [21]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [22]:
array2d = np.array([[8,12],[7,1]])
print(array2d)

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [23]:
org_array = np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)
print(sort_indices)

[1 3 5 9]
[1 0 3 2]


In [24]:
org_array = np.array([3,1,9,5])
print(np.sort(org_array)[::-1])

sort_indices = np.argsort(org_array)[::-1]
print(sort_indices)

[9 5 3 1]
[2 3 0 1]


In [26]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indicies = np.argsort(score_array)
print(sort_indicies)

name_array_sort = name_array[sort_indicies]

score_array_sort = score_array[sort_indicies]
print(name_array_sort)
print(score_array_sort)

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


In [27]:
A = np.array([[1,2,3],[4,5,6]])
B= np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [28]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
